/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAX_H_RPCGEN
#define _MAX_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int size;
	int a[20];
};
typedef struct numbers numbers;

struct ret {
	int maxno;
	int minno;
	float avgno;
};
typedef struct ret ret;

#define MMA_PROG 0x4562877
#define MMA_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MMA 1
extern  ret * mma_1(numbers *, CLIENT *);
extern  ret * mma_1_svc(numbers *, struct svc_req *);
extern int mma_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MMA 1
extern  ret * mma_1();
extern  ret * mma_1_svc();
extern int mma_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);
extern  bool_t xdr_ret (XDR *, ret*);

#else /* K&R C */
extern bool_t xdr_numbers ();
extern bool_t xdr_ret ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MAX_H_RPCGEN */
