/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "max.h"

void mma_prog_1(char *host,int size, int arr[])
{
	CLIENT *clnt;
	ret  *result_1;
	numbers  mma_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MMA_PROG, MMA_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	for (int i = 0; i < size; i++)
	{
		mma_1_arg.a[i] = arr[i];
	}
	for (int i = 0; i < size; i++)
	{
		printf("%d ", mma_1_arg.a[i]);
	}
	mma_1_arg.size = size;
	// result_1 = maxint_1(&maxint_1_arg, clnt);
	result_1 = mma_1(&mma_1_arg, clnt);
	if (result_1 == (ret *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("Maximum number = %d, Minimum Number = %d, Average number = %f", result_1->maxno, result_1->minno, result_1->avgno);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	host = argv[1];
	int size = atoi(argv[2]);
	// int size = argc;

	if (argc < size + 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	int arr[20];
	for (int i = 0; i < size; i++)
	{
		arr[i] = atoi(argv[3 + i]);
	}
	mma_prog_1(host, size, arr);
	return 0;
}
