/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "max.h"

ret *
mma_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static ret result;

	/*
	 * insert server code here
	 */

	for (int i = 0; i < argp->size; i++)
	{
		printf("%d ", argp->a[i]);
	}
	printf(") is called.\n");
	int max = argp->a[0],min=argp->a[0];
	float sum = argp->a[0];
	for (int i = 1; i < argp->size; i++)
	{
		if (max < argp->a[i])
		{
			max = argp->a[i];
		}
		if (min > argp->a[i])
		{
			min = argp->a[i];
		}
		sum += argp->a[i];
	}
	result.avgno = sum / argp->size;
	result.maxno = max;
	result.minno = min;
	return &result;
}
