/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

int *
calc_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	char op = argp->sym;
	printf("calc(%d,%c,%d) is called\n", argp->a, argp->sym,argp->b);
	switch (op)
	{
	case '+':
		result = argp->a + argp->b;
		break;

	case '-':
		result = argp->a - argp->b;
		break;

	case 'x':
		result = argp->a * argp->b;
		break;

	case '/':
		result = argp->a / argp->b;
		break;

	case '%':
		result = argp->a % argp->b;
		break;

	default:
		printf("unknown character\n");
		break;
	}

	return &result;
}
