/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

void calc_prog_1(char *host, int x, char op, int y)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  calc_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, calc_PROG, calc_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	calc_1_arg.a=x;
	calc_1_arg.b=y;
	calc_1_arg.sym=op;
	result_1 = calc_1(&calc_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("Result: %d\n", *result_1);
	}
#ifndef DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 5) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calc_prog_1(host, atoi(argv[2]), argv[3][0], atoi(argv[4])) ;
	exit(0);
}
