/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fibo.h"

void fibo_prog_1(char *host, int x)
{
	CLIENT *clnt;
	int *result_1;
	numbers fibo_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, FIBO_PROG, FIBO_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */
	fibo_1_arg.a = x;
	result_1 = fibo_1(&fibo_1_arg, clnt);
	if (result_1 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("Fibonacci Series: ");
		int n1 = 0, n2 = 1, n3,number = *result_1;
		printf(" 0 1");
		for (int i = 2; i < number; ++i) // loop starts from 2 because 0 and 1 are already printed
		{
			n3 = n1 + n2;
			printf(" %d", n3);
			n1 = n2;
			n2 = n3;
		}
		printf("\n");
	}
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;

	if (argc < 3)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	fibo_prog_1(host, atoi(argv[2]));
	exit(0);
}
