/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fibo.h"

int *
fibo_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("fibo(%d) is called\n",argp->a);
	result = argp->a;
	/*
	 * insert server code here
	 */

	return &result;
}
