/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "subs.h"

int *substring_1_svc(strpair *argp, struct svc_req *rqstp)
{
	static int result;

	printf("Substring check is called for two strinsgs\n");

	int l1 = strlen(argp->a);
	int l2 = strlen(argp->b);
	printf("%s , %s \n", argp->a, argp->b);
	for (int i = 0; i <= l2 - l1; i++)
	{
		int j;
		for (j = 0; j < l1; j++)
			if (argp->b[i + j] != argp->a[j])
				break;

		if (j == l1)
		{
			result = 1;
			return &result;
		}
	}
	result = 0;
	return &result;
}
