/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PRIME_H_RPCGEN
#define _PRIME_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int a;
};
typedef struct numbers numbers;

#define PRIME_PROG 0x4562877
#define PRIME_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define prime 1
extern  int * prime_1(numbers *, CLIENT *);
extern  int * prime_1_svc(numbers *, struct svc_req *);
extern int prime_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define prime 1
extern  int * prime_1();
extern  int * prime_1_svc();
extern int prime_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PRIME_H_RPCGEN */
