/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prime.h"

int *prime_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int result ;

	/*
	 * insert server code here
	 */
	int flg = 0;
	printf("prime(%d) is called \n", argp->a);
	for (int i = 2; i <= (argp->a / 2); i++)
	{
		if (argp->a % i==0)
		{
			flg = 1;
			break;
		}
	}
	result = flg;
	return &result;
}
