/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "conc.h"

str *
conc_1_svc(strpair *argp, struct svc_req *rqstp)
{
	static str  result;
	int i;
	for (i = 0; argp->a[i] != '\0'; i++)
	{
		result.ans[i] = argp->a[i];
	}
	for  (int j=0; argp->b[j];i++, j++)
	{
		/* code */
		result.ans[i] = argp->b[j];
	}
	result.ans[i] = '\0';
	return &result;
}
