/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gcd.h"

int *
gcd_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	int gc;
	for (int i = 1; i <= argp->a && i <= argp->b; ++i)
	{
		if(argp->a%i==0&&argp->b%i==0){
			gc = i;
		}
	}
	// printf("%d %d %d \n",argp->a,argp->b,gc);
	result = gc;
	return &result;
}
