/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PAL_H_RPCGEN
#define _PAL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct strings {
	char a[50];
};
typedef struct strings strings;

#define PAL_PROG 0x4562877
#define PAL_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define pal 1
extern  int * pal_1(strings *, CLIENT *);
extern  int * pal_1_svc(strings *, struct svc_req *);
extern int pal_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define pal 1
extern  int * pal_1();
extern  int * pal_1_svc();
extern int pal_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_strings (XDR *, strings*);

#else /* K&R C */
extern bool_t xdr_strings ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PAL_H_RPCGEN */
