/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pal.h"


void
pal_prog_1(char *host,char a[])
{
	CLIENT *clnt;
	int  *result_1;
	strings  pal_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PAL_PROG, PAL_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	// printf("hey %s", a);

	int c = 0;
	while (a[c] != '\0')
	{
		pal_1_arg.a[c] = a[c];
		c++;
	}
	pal_1_arg.a[c] = '\0';
	// printf("hey %s", pal_1_arg.a);
	result_1 = pal_1(&pal_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		if(*result_1==1){
			printf("%s is a palindrome\n", a);
		}
		else{
			printf("%s is not a palindrome\n", a);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int
main (int argc, char *argv[])
{
	char *host;
	if (argc < 3) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	pal_prog_1 (host,argv[2]);
exit (0);
}
