/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pal.h"

int *pal_1_svc(strings *argp, struct svc_req *rqstp)
{
	static int result;
	int l = 0;
	int flg = 1;
	int h = strlen(argp->a) - 1;

	while (h > l)
	{
		if (argp->a[l++] != argp->a[h--])
		{
			result = 0;
			return &result;
		}
	}
	result = 1;
	return &result;
}
