/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "leap.h"

int *
leap_1_svc(years *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	if (argp->year % 4 == 0)
	{
		if (argp->year % 400 == 0)
		{
			result = 1;
		}
		else if (argp->year % 100 == 0)
		{
			result = 0;
		}
		else
		{
			result = 1;
		}
	}
	else
	{
		result = 0;
	}

	return &result;
}
