/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REV_H_RPCGEN
#define _REV_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct arr {
	int size;
	int a[50];
};
typedef struct arr arr;

#define REV_PROG 0x4562877
#define REV_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define rev 1
extern  arr * rev_1(arr *, CLIENT *);
extern  arr * rev_1_svc(arr *, struct svc_req *);
extern int rev_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define rev 1
extern  arr * rev_1();
extern  arr * rev_1_svc();
extern int rev_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_arr (XDR *, arr*);

#else /* K&R C */
extern bool_t xdr_arr ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REV_H_RPCGEN */
