/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rev.h"

void rev_prog_1(char *host, int size, int ar[])
{
	CLIENT *clnt;
	arr *result_1;
	arr rev_1_arg;
#ifndef DEBUG
	clnt = clnt_create(host, REV_PROG, REV_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */
	for (int i = 0; i < size; i++)
	{
		rev_1_arg.a[i] = ar[i];
	}
	rev_1_arg.size = size;
	result_1 = rev_1(&rev_1_arg, clnt);
	if (result_1 == (arr *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		for (int i = 0; i < size; i++)
		{
			printf("%d ", result_1->a[i]);
		}
	}
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;
	int size = atoi(argv[2]);
	int ar[50];

	if (argc < size + 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	for (int i = 0; i < size; i++)
	{
		ar[i] = atoi(argv[3 + i]);
	}

	host = argv[1];
	rev_prog_1(host, size, ar);
	exit(0);
}
