/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAXINT_H_RPCGEN
#define _MAXINT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int size;
	int a[20];
};
typedef struct numbers numbers;

#define MAXINT_PROG 0x4562877
#define MAXINT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MAXINT 1
extern  int * maxint_1(numbers *, CLIENT *);
extern  int * maxint_1_svc(numbers *, struct svc_req *);
extern int maxint_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MAXINT 1
extern  int * maxint_1();
extern  int * maxint_1_svc();
extern int maxint_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MAXINT_H_RPCGEN */
