/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "maxint.h"

void maxint_prog_1(char *host,int size,int arr[])
{
	CLIENT *clnt;
	int *result_1;
	numbers maxint_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, MAXINT_PROG, MAXINT_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	// memcpy(maxint_1_arg.a, arr, sizeof(arr));

	for (int i = 0; i < size; i++)
	{
		maxint_1_arg.a[i] = arr[i];
	}
	// for (int i = 0; i < size; i++)
	// {
	// 	printf("%d ", maxint_1_arg.a[i]);
	// }
	maxint_1_arg.size = size;
	result_1 = maxint_1(&maxint_1_arg, clnt);
	if (result_1 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else{
		printf("Max element: %d\n", *result_1);
	}
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;
	host = argv[1];
	// int size = atoi(argv[2]);
	int size=argc
	

	if (argc < size + 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	} 
	int arr[20];
	for (int i = 0; i < size; i++)
	{
		arr[i] = atoi(argv[3 + i]);
	}
	maxint_prog_1(host,size,arr);
	exit(0);
}
