/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "maxint.h"

int *maxint_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int result;
	int size = argp->size, max;

	// int a[size];

	// for (int i = 0; i < size; i++)
	// {
	// 	maxint_1_arg.a[i] = arr[i];
	// }
	printf("maxint(%d, ", size);
	for (int i = 0; i < size;i++){
		printf("%d ", argp->a[i]);
	}
	printf(") is called.\n");
	max = argp->a[0];
	for (int i = 1; i < size; i++)
	{
		if (max < argp->a[i])
		{
			max = argp->a[i];
		}
	}
	result = max;
	return &result;
}
