/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "swap.h"

numbers *swap_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static numbers result;

	/*
	 * insert server code here
	 */
	result.a = argp->b;
	result.b = argp->a;
	return &result;
}
