/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cmp.h"

int *cmp_1_svc(strpair *argp, struct svc_req *rqstp)
{
	static int result;
	result = strcmp(argp->a, argp->b);
	return &result;
}
