/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "factorial.h"

int *
factorial_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	int re = 1;
	printf("fact(%d) is called\n", argp->a);
	for (int i = 1; i <= argp->a; i++)
	{
		re *= i;
	}
	result = re;
	return &result;
}
